use std::fmt::Write as _;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::{Component, Path, PathBuf};

use serde_json::{Map, Value, json};

const SCHEMA_VERSION: u64 = 1;

const MARKDOWN_HEADER: &str = r#"# MCP Console session transcript

<!-- Generated by MCP Console. Do not edit. -->

This document is an append-only chronological record of MCP Console events.

"#;

pub(super) struct Writers {
    markdown: Option<ProjectionWriter>,
    quarto: Option<QuartoWriter>,
}

struct ProjectionWriter {
    writer: BufWriter<File>,
    header_written: bool,
    description: &'static str,
}

struct QuartoWriter {
    path: PathBuf,
    r_requirements: Vec<String>,
    python_requirements: Vec<String>,
    sources: Vec<QuartoSource>,
}

struct QuartoSource {
    language: &'static str,
    contents: String,
}

impl Writers {
    pub(super) fn new(markdown: Option<File>, quarto: Option<PathBuf>) -> Self {
        Self {
            markdown: markdown.map(|file| ProjectionWriter::new(file, "Markdown transcript")),
            quarto: quarto.map(QuartoWriter::new),
        }
    }

    pub(super) fn append(&mut self, event: &Value) -> Result<(), String> {
        if self.markdown.is_none() && self.quarto.is_none() {
            return Ok(());
        }
        if let Err(error) = validate_envelope(event) {
            self.markdown = None;
            self.quarto = None;
            return Err(error);
        }
        let markdown = append_rendered(&mut self.markdown, MARKDOWN_HEADER, event, render_event);
        let quarto = update_quarto(&mut self.quarto, event);
        markdown.or(quarto).map_or(Ok(()), Err)
    }
}

fn update_quarto(projection: &mut Option<QuartoWriter>, event: &Value) -> Option<String> {
    let writer = projection.as_mut()?;
    if let Err(error) = writer.append(event) {
        *projection = None;
        return Some(error);
    }
    None
}

impl QuartoWriter {
    fn new(path: PathBuf) -> Self {
        Self {
            path,
            r_requirements: crate::worker_client::DEFAULT_R_REQUIREMENTS
                .iter()
                .map(|requirement| (*requirement).to_string())
                .collect(),
            python_requirements: crate::worker_protocol::DEFAULT_PYTHON_PACKAGES
                .iter()
                .map(|requirement| (*requirement).to_string())
                .collect(),
            sources: Vec::new(),
        }
    }

    fn append(&mut self, event: &Value) -> Result<(), String> {
        let changed = match string(field(event, "event")?, "event kind")? {
            "session_started" => true,
            "tool_call" => {
                let Some(request) = event.get("request").and_then(Value::as_object) else {
                    return Ok(());
                };
                let mut changed = false;
                if let Some(requirements) = declared_requirements(request) {
                    extend_unique(&mut self.r_requirements, requirements.r);
                    extend_unique(&mut self.python_requirements, requirements.python);
                    changed = true;
                }
                if let Some(source) = submitted_source(request) {
                    self.sources.push(QuartoSource {
                        language: source.language,
                        contents: source.contents.to_string(),
                    });
                    changed = true;
                }
                changed
            }
            "artifact_created" | "tool_result" => false,
            kind => {
                return Err(format!(
                    "Quarto source transcript has unsupported event kind {kind:?}"
                ));
            }
        };
        if !changed {
            return Ok(());
        }
        let document = self.render();
        super::replace_private_file(&self.path, document.as_bytes())
    }

    fn render(&self) -> String {
        let mut document = String::from(
            r#"---
# Generated by MCP Console. Do not edit.
title: MCP Console code cells
ir:
  isolated: true
"#,
        );
        push_yaml_sequence(&mut document, "  packages", &self.r_requirements);
        push_yaml_sequence(
            &mut document,
            "  python-packages",
            &self.python_requirements,
        );
        document.push_str("---\n\n");
        for source in &self.sources {
            let language = format!("{{{}}}", source.language);
            push_fence(&mut document, &language, &source.contents);
        }
        document
    }
}

struct DeclaredRequirements<'a> {
    r: Vec<&'a str>,
    python: Vec<&'a str>,
}

fn declared_requirements(request: &Map<String, Value>) -> Option<DeclaredRequirements<'_>> {
    if request.get("name")?.as_str()? != "send" {
        return None;
    }
    let requirements = request
        .get("arguments")?
        .as_object()?
        .get("requirements")?
        .as_object()?;
    let r = requirement_strings(requirements, "r")?;
    let python = requirement_strings(requirements, "python")?;
    if r.is_empty() && python.is_empty() {
        return None;
    }
    Some(DeclaredRequirements { r, python })
}

fn requirement_strings<'a>(
    requirements: &'a Map<String, Value>,
    language: &str,
) -> Option<Vec<&'a str>> {
    match requirements.get(language) {
        Some(values) => values.as_array()?.iter().map(Value::as_str).collect(),
        None => Some(Vec::new()),
    }
}

fn extend_unique<'a>(requirements: &mut Vec<String>, additions: impl IntoIterator<Item = &'a str>) {
    for requirement in additions {
        if !requirements.iter().any(|existing| existing == requirement) {
            requirements.push(requirement.to_string());
        }
    }
}

fn push_yaml_sequence(document: &mut String, name: &str, values: &[String]) {
    if values.is_empty() {
        writeln!(document, "{name}: []").expect("writing to a String cannot fail");
        return;
    }
    writeln!(document, "{name}:").expect("writing to a String cannot fail");
    for value in values {
        let value = yaml_string(value);
        writeln!(document, "    - {value}").expect("writing to a String cannot fail");
    }
}

fn yaml_string(value: &str) -> String {
    if is_plain_yaml_string(value) {
        value.to_string()
    } else {
        serde_json::to_string(value).expect("serializing a string cannot fail")
    }
}

fn is_plain_yaml_string(value: &str) -> bool {
    let Some(first) = value.chars().next() else {
        return false;
    };
    if !matches!(first, 'A'..='Z' | 'a'..='z' | '_')
        || value.chars().any(char::is_control)
        || value.trim() != value
        || value.ends_with(':')
        || value
            .chars()
            .zip(value.chars().skip(1))
            .any(|(previous, character)| previous.is_whitespace() && character == '#')
        || value
            .split(':')
            .skip(1)
            .any(|suffix| suffix.starts_with(char::is_whitespace))
    {
        return false;
    }
    !matches!(
        value.to_ascii_lowercase().as_str(),
        "null" | "true" | "false"
    )
}

fn append_rendered(
    projection: &mut Option<ProjectionWriter>,
    header: &str,
    event: &Value,
    render: fn(&mut String, &Value) -> Result<(), String>,
) -> Option<String> {
    let writer = projection.as_mut()?;
    let mut fragment = String::new();
    let result = render(&mut fragment, event).and_then(|()| writer.append(header, &fragment));
    match result {
        Ok(()) => None,
        Err(error) => {
            *projection = None;
            Some(error)
        }
    }
}

impl ProjectionWriter {
    fn new(file: File, description: &'static str) -> Self {
        Self {
            writer: BufWriter::new(file),
            header_written: false,
            description,
        }
    }

    fn append(&mut self, header: &str, fragment: &str) -> Result<(), String> {
        if !self.header_written {
            self.writer
                .write_all(header.as_bytes())
                .map_err(|error| format!("failed to append {}: {error}", self.description))?;
        }
        self.writer
            .write_all(fragment.as_bytes())
            .and_then(|()| self.writer.flush())
            .map_err(|error| format!("failed to append {}: {error}", self.description))?;
        self.header_written = true;
        Ok(())
    }
}

fn render_event(document: &mut String, event: &Value) -> Result<(), String> {
    match string(field(event, "event")?, "event kind")? {
        "session_started" => render_session_started(document, event),
        "tool_call" => render_tool_call(document, event),
        "artifact_created" => render_artifact(document, event),
        "tool_result" => render_tool_result(document, event),
        kind => Err(format!(
            "Markdown transcript has unsupported event kind {kind:?}"
        )),
    }
}

fn validate_envelope(event: &Value) -> Result<(), String> {
    object(event, "event")?;
    let schema_version = number(event, "schema_version")?;
    if schema_version != SCHEMA_VERSION {
        return Err(format!(
            "Markdown transcript has unsupported schema version {schema_version}"
        ));
    }
    string(field(event, "run_id")?, "run ID")?;
    number(event, "sequence")?;
    string(field(event, "at")?, "event timestamp")?;
    Ok(())
}

fn render_session_started(document: &mut String, event: &Value) -> Result<(), String> {
    let metadata = json!({
        "session": string(field(event, "session")?, "session name")?,
        "run_id": string(field(event, "run_id")?, "run ID")?,
        "started_at": string(field(event, "at")?, "session timestamp")?,
        "working_directory": string(
            field(event, "working_directory")?,
            "working directory",
        )?,
    });
    document.push_str("## Session\n\n");
    push_json(document, &metadata)
}

fn render_tool_call(document: &mut String, event: &Value) -> Result<(), String> {
    let call_id = number(event, "call_id")?;
    field(event, "request_id")?;
    let request = object(field(event, "request")?, "tool request")?;
    let Some(send) = parse_send(request) else {
        writeln!(document, "## Call {call_id}: Tool request\n")
            .expect("writing to a String cannot fail");
        if let Some(source) = submitted_source(request) {
            push_fence(document, source.language, source.contents);
            document.push_str("### Raw request\n\n");
        }
        return push_json(document, &Value::Object(request.clone()));
    };

    let label = send.label();
    writeln!(document, "## Call {call_id}: {label}\n").expect("writing to a String cannot fail");
    if let Some(source) = send.source {
        push_fence(document, source.language, source.contents);
    }
    if let Some(stdin) = send.stdin {
        document.push_str("### Submitted stdin\n\n");
        push_fence(document, "text", stdin);
    }
    if !send.options.is_empty() {
        document.push_str("### Options\n\n");
        push_json(document, &Value::Object(send.options))?;
    }
    Ok(())
}

struct Send<'a> {
    source: Option<Source<'a>>,
    stdin: Option<&'a str>,
    options: Map<String, Value>,
}

impl Send<'_> {
    fn label(&self) -> &'static str {
        if let Some(source) = self.source {
            return source.label;
        }
        match self.options.get("control").and_then(Value::as_str) {
            Some("interrupt") => return "Interrupt",
            Some("restart") => return "Restart",
            _ => {}
        }
        if self.stdin.is_some() {
            return "Stdin";
        }
        if self.options.contains_key("requirements") {
            return "Requirements";
        }
        if self.options.is_empty() || self.options.keys().all(|key| key == "timeout_ms") {
            "Poll"
        } else {
            "Send"
        }
    }
}

#[derive(Clone, Copy)]
struct Source<'a> {
    label: &'static str,
    language: &'static str,
    contents: &'a str,
}

fn submitted_source(request: &Map<String, Value>) -> Option<Source<'_>> {
    if request.get("name")?.as_str()? != "send" {
        return None;
    }
    let arguments = request.get("arguments")?.as_object()?;
    let mut source = None;
    for (field, label, language) in [
        ("r", "R", "r"),
        ("python", "Python", "python"),
        ("sql", "SQL", "sql"),
    ] {
        let Some(value) = arguments.get(field) else {
            continue;
        };
        let value = value.as_str()?;
        if source
            .replace(Source {
                label,
                language,
                contents: value,
            })
            .is_some()
        {
            return None;
        }
    }
    source
}

fn parse_send(request: &Map<String, Value>) -> Option<Send<'_>> {
    if request.get("name")?.as_str()? != "send"
        || request
            .keys()
            .any(|key| !matches!(key.as_str(), "name" | "arguments" | "_meta"))
    {
        return None;
    }
    let arguments = match request.get("arguments") {
        Some(arguments) => arguments.as_object()?,
        None => {
            return Some(Send {
                source: None,
                stdin: None,
                options: Map::new(),
            });
        }
    };
    if arguments.keys().any(|key| {
        !matches!(
            key.as_str(),
            "r" | "python" | "sql" | "stdin" | "control" | "requirements" | "timeout_ms"
        )
    }) {
        return None;
    }
    let mut source = None;
    for (field, label, language) in [
        ("r", "R", "r"),
        ("python", "Python", "python"),
        ("sql", "SQL", "sql"),
    ] {
        let Some(value) = arguments.get(field) else {
            continue;
        };
        let value = value.as_str()?;
        if source
            .replace(Source {
                label,
                language,
                contents: value,
            })
            .is_some()
        {
            return None;
        }
    }
    let stdin = match arguments.get("stdin") {
        Some(stdin) => Some(stdin.as_str()?),
        None => None,
    };
    let options = arguments
        .iter()
        .filter(|(key, _)| !matches!(key.as_str(), "r" | "python" | "sql" | "stdin"))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    Some(Send {
        source,
        stdin,
        options,
    })
}

fn render_artifact(document: &mut String, event: &Value) -> Result<(), String> {
    let artifact_id = number(event, "artifact_id")?;
    let call_id = number(event, "call_id")?;
    let path = artifact_path(field(event, "path")?)?;
    string(field(event, "mime_type")?, "artifact MIME type")?;
    number(event, "bytes")?;
    writeln!(
        document,
        "## Artifact {artifact_id} for call {call_id}\n\n[Artifact {artifact_id} from call {call_id}](<{path}>)\n"
    )
    .expect("writing to a String cannot fail");
    Ok(())
}

fn render_tool_result(document: &mut String, event: &Value) -> Result<(), String> {
    let call_id = number(event, "call_id")?;
    writeln!(document, "## Result for call {call_id}\n").expect("writing to a String cannot fail");
    match (event.get("result"), event.get("error")) {
        (Some(result), None) => render_result(document, call_id, result),
        (None, Some(error)) => {
            object(error, "tool error")?;
            document.push_str("### Tool error\n\n");
            push_json(document, error)
        }
        _ => Err(format!(
            "Markdown transcript has invalid result event for call {call_id}"
        )),
    }
}

fn render_result(document: &mut String, call_id: u64, result: &Value) -> Result<(), String> {
    let result = object(result, "tool result")?;
    if let Some(is_error) = result.get("isError")
        && bool_value(is_error, "tool result error flag")?
    {
        document.push_str("### Tool result error\n\n");
    }
    let content = result
        .get("content")
        .ok_or_else(|| format!("Markdown transcript result for call {call_id} has no content"))?
        .as_array()
        .ok_or_else(|| format!("Markdown transcript content for call {call_id} is not an array"))?;
    if content.is_empty() {
        document.push_str("_No content._\n\n");
    }
    for block in content {
        let block = object(block, "content block")?;
        match string(field_map(block, "type")?, "content block type")? {
            "text" => push_fence(
                document,
                "text",
                string(field_map(block, "text")?, "text content")?,
            ),
            "image" => {
                let artifact_id = unsigned(field_map(block, "artifactId")?, "artifact ID")?;
                let path = artifact_path(field_map(block, "path")?)?;
                string(field_map(block, "mimeType")?, "image MIME type")?;
                writeln!(document, "![Artifact {artifact_id}](<{path}>)\n")
                    .expect("writing to a String cannot fail");
            }
            kind => {
                return Err(format!(
                    "Markdown transcript has unsupported content kind {kind:?} for call {call_id}"
                ));
            }
        }
    }
    Ok(())
}

fn push_json(document: &mut String, value: &Value) -> Result<(), String> {
    let json = serde_json::to_string_pretty(value)
        .map_err(|error| format!("failed to render Markdown transcript JSON: {error}"))?;
    push_fence(document, "json", &json);
    Ok(())
}

fn push_fence(document: &mut String, language: &str, contents: &str) {
    let longest = contents
        .split(|character| character != '`')
        .map(str::len)
        .max()
        .unwrap_or_default();
    let fence = "`".repeat((longest + 1).max(3));
    writeln!(document, "{fence}{language}").expect("writing to a String cannot fail");
    document.push_str(contents);
    if !contents.ends_with('\n') {
        document.push('\n');
    }
    writeln!(document, "{fence}\n").expect("writing to a String cannot fail");
}

fn artifact_path(value: &Value) -> Result<&str, String> {
    let path = string(value, "artifact path")?;
    if path.is_empty()
        || path
            .chars()
            .any(|character| matches!(character, '\0' | '\n' | '\r' | '<' | '>'))
        || Path::new(path)
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
    {
        return Err("Markdown transcript artifact path is not a safe relative path".to_string());
    }
    Ok(path)
}

fn field<'a>(value: &'a Value, name: &str) -> Result<&'a Value, String> {
    value
        .get(name)
        .ok_or_else(|| format!("Markdown transcript value has no {name}"))
}

fn field_map<'a>(value: &'a Map<String, Value>, name: &str) -> Result<&'a Value, String> {
    value
        .get(name)
        .ok_or_else(|| format!("Markdown transcript value has no {name}"))
}

fn object<'a>(value: &'a Value, name: &str) -> Result<&'a Map<String, Value>, String> {
    value
        .as_object()
        .ok_or_else(|| format!("Markdown transcript {name} is not an object"))
}

fn string<'a>(value: &'a Value, name: &str) -> Result<&'a str, String> {
    value
        .as_str()
        .ok_or_else(|| format!("Markdown transcript {name} is not a string"))
}

fn number(value: &Value, name: &str) -> Result<u64, String> {
    unsigned(field(value, name)?, name)
}

fn unsigned(value: &Value, name: &str) -> Result<u64, String> {
    value
        .as_u64()
        .ok_or_else(|| format!("Markdown transcript {name} is not an unsigned integer"))
}

fn bool_value(value: &Value, name: &str) -> Result<bool, String> {
    value
        .as_bool()
        .ok_or_else(|| format!("Markdown transcript {name} is not a boolean"))
}
